[FE-49]feat: 파일 추가 기능구현
ItRecode/recodeIt-client pull request #31
Opened 2022-12-26 09:17 UTC by endmoseung

## 작업 내용
-파일 추가 기능구현
-관련 디자인도 구현

## 참고 이미지(선택)
![image](https://user-images.githubusercontent.com/103626175/209530613-aeb406fe-c8f8-4fec-ba30-1d3954d8ca8e.png)

## 어떤 점을 리뷰 받고 싶으신가요?
자유롭게 부탁드립니다!

2022-12-26 14:06 UTC, sukyeongh requested changes
모승 파일 적용구현 잘 보았습니다 :)
제가 생각하는 변경해야할 부분들 모두 리뷰로 적어두었습니다. 확인 부탁드려요!

2022-12-26 14:06 UTC, sukyeongh commented on src/pages/AddRecord/AddRecordFile.tsx
> +  const [currentImg, setCurrentImg] = useState<null | string>(null)
`currentImg`에서 null말고 `''`빈 문자열로 구현하는 것은 안되나요? string 타입만으로도 가능하다고 생각합니다.

2022-12-26 14:06 UTC, sukyeongh commented on src/pages/AddRecord/AddRecordFile.tsx
> +  const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => {
변수명으로 `handleSelectImageFile`처럼 길게 작성하면 어떨까요? :)

2022-12-26 14:06 UTC, sukyeongh commented on src/pages/AddRecord/AddRecordFile.tsx
> +    })
여기서 실패하면 어떻게 되나요?

2022-12-26 14:06 UTC, sukyeongh commented on src/pages/AddRecord/AddRecordFile.tsx
> +            <span className={`text-${!currentImg ? 'gray-400' : 'primary-2'}`}>
제가 지금까지 클래스 네임을 주의깊게 보지 않았나보네요ㅠㅠ
`gray-400`처럼 tailwind에서 주어지는 색상 말고 저희가 직접 지정한 grey-number 로 색깔 지정해주세요.

이 부분말고 다른부분도 저희 색상으로 적용되지 않은 부분은 전부다 변경했으면 좋겠습니다

2022-12-26 14:06 UTC, sukyeongh commented on src/pages/AddRecord/AddRecordFile.tsx
> +        disabled={currentImg !== null && true}
`&& ture`는 왜 사용하시는건가요?

2022-12-26 14:06 UTC, sukyeongh commented on src/pages/AddRecord/AddRecordFile.tsx
> +            alt={currentImg}
alt는 이미지가 무엇인지 설명해주는 속성입니다. `user-selected-record-image`처럼 설명하면 좋을 것 같아요

2022-12-26 17:10 UTC, endmoseung commented on src/pages/AddRecord/AddRecordFile.tsx
> +import { ReactComponent as Xbutton } from '@assets/Xbutton.svg'
좋아요! x는 너무 추상적이네요

2022-12-26 17:10 UTC, endmoseung commented on src/pages/AddRecord/AddRecordFile.tsx
> +  const [currentImg, setCurrentImg] = useState<null | string>(null)
이거는 이미지가 안 들어있는상태에서 빈 문자열보다는 null이나 undefined를 넣어주는게 더 문맥상 맞다고 생각해요

2022-12-26 17:10 UTC, endmoseung commented on src/pages/AddRecord/AddRecordFile.tsx
> +  const handleFile = (e: React.ChangeEvent<HTMLInputElement>) => {
이거는 동의합니다 반영할게용

2022-12-26 17:10 UTC, endmoseung commented on src/pages/AddRecord/AddRecordFile.tsx
> +    })
음 이거 코드 그대로 받아온건데 실패했을때는 then으로 error를 띄우는게 맞을까요??

2022-12-26 17:10 UTC, endmoseung commented on src/pages/AddRecord/AddRecordFile.tsx
> +            <span className={`text-${!currentImg ? 'gray-400' : 'primary-2'}`}>
아하 알겠습니다 일단 여기 다 바꿀게용

2022-12-26 17:10 UTC, endmoseung commented on src/pages/AddRecord/AddRecordFile.tsx
> +        disabled={currentImg !== null && true}
이게 최소 하나를 올렸을때 다시 버튼이 클릭되면 안되게 해달라고 디자이너분이 부탁해서 disable에 true를 준거에여

2022-12-26 17:10 UTC, endmoseung commented on src/pages/AddRecord/AddRecordFile.tsx
> +            alt={currentImg}
<img width="935" alt="image" src="https://user-images.githubusercontent.com/103626175/209570457-abf58f8c-0d69-40b3-a83c-983f94c01d31.png">
맞네용 제가 alt가 뭔지 잘 몰랐는데 이번에 배워가요 이거 변경할게용! 감사합니다.

2022-12-26 17:15 UTC, sukyeongh commented on src/pages/AddRecord/AddRecordFile.tsx
> +    })
에러도 띄우고 사용자한테도 알려주는 방법이 있어야 할 것 같은데 디자이너님께 여쭤봐야할 것 같아요

2022-12-26 17:15 UTC, sukyeongh commented on src/pages/AddRecord/AddRecordFile.tsx
> +        disabled={currentImg !== null && true}
`currentImg !== null`로만 충분하지 않나요?

2022-12-27 00:14 UTC, endmoseung commented on src/pages/AddRecord/AddRecordFile.tsx
> +        disabled={currentImg !== null && true}
앗 맞네요! 반영하겠습니다

2022-12-27 06:42 UTC, Seongtaek-H approved these changes
확인했습니닷 생소한 타입이 많아서 좀 어렵네여

2022-12-27 08:11 UTC, sukyeongh approved these changes
확인했습니다 :)

2022-12-28 01:14 UTC, merged