[FE-94]feat: 축하 위로 탭 디자인 재적용
ItRecode/recodeIt-client pull request #76
Opened 2023-01-12 05:25 UTC by endmoseung

## 작업 내용
-디자인에 맞게 재 수정
## 참고 이미지(선택)
![image](https://user-images.githubusercontent.com/103626175/211984440-cdecb049-0c9b-4a74-ac63-5e82ce64a60d.png)

## 어떤 점을 리뷰 받고 싶으신가요?

2023-01-12 05:47 UTC, sukyeongh requested changes
넵 모승 확인했습니다

이 부분은 margin, padding으로 작업하시는 것이아닌 축하와 위로를 전체 레이아웃 width의 반으로 나누고 각 탭이 중앙정렬 되어있어야 해야한다고 생각합니다!

2023-01-12 05:59 UTC, Seongtaek-H approved these changes
확인용

2023-01-12 06:15 UTC, endmoseung commented
> 넵 모승 확인했습니다
> 
> 이 부분은 margin, padding으로 작업하시는 것이아닌 축하와 위로를 전체 레이아웃 width의 반으로 나누고 각 탭이 중앙정렬 되어있어야 해야한다고 생각합니다!

지금 히니한테 물어봤는데 답오는대로 바꿔야한다면 바꿔서 머지할게여

2023-01-13 04:23 UTC, sukyeongh approved these changes
넵 확인했습니당

2023-01-13 04:41 UTC, merged